import './globals.css'
import { Inter } from 'next/font/google'

import { Providers } from '@/GlobalRedux/prodiver'
import Sidebar from '@/components/sidebar/Sidebar'
import Navbar from '@/components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Sidebar>
            <Navbar />
            {children}
            </Sidebar>
        </Providers>
      </body>
    </html>
  )
}
